In [35]:
import numpy as np
import pandas as pd

In [36]:
# Historical Weather DataSet Pre-processing-EDA
# OR using raw string
weather_df = pd.read_csv(r"C:\Users\chimi\Desktop\Python Data Science Projects\Cocoa Production\Data -1\Ghana Weather dataset 2010-01-01 to 2023-06-03.csv")

In [37]:
weather_df.head(5)

,name,datetime,tempmax,tempmin,temp,feelslikemax,feelslikemin,feelslike,dew,humidity,...,solarenergy,uvindex,severerisk,sunrise,sunset,moonphase,conditions,description,icon,stations
0,Ashanti Ghana,2010-01-01,34.2,23.0,27.9,36.1,23.0,29.3,21.9,73.4,...,18.1,8,NaN,2010-01-01T06:17:45,2010-01-01T18:02:18,0.52,Partially cloudy,Partly cloudy throughout the day.,partly-cloudy-day,"remote,65442099999"
1,Ashanti Ghana,2010-01-02,34.6,23.4,28.1,36.5,23.4,29.5,21.7,71.1,...,18.4,7,NaN,2010-01-02T06:18:11,2010-01-02T18:02:49,0.56,Partially cloudy,Partly cloudy throughout the day.,partly-cloudy-day,"remote,65442099999"
2,Ashanti Ghana,2010-01-03,35.8,23.7,28.5,36.9,23.7,29.7,21.3,69.0,...,19.1,8,NaN,2010-01-03T06:18:35,2010-01-03T18:03:20,0.59,Partially cloudy,Partly cloudy throughout the day.,partly-cloudy-day,"remote,65442099999"
3,Ashanti Ghana,2010-01-04,35.2,23.4,28.2,35.3,23.4,28.9,20.6,68.2,...,18.5,8,NaN,2010-01-04T06:18:59,2010-01-04T18:03:51,0.63,Partially cloudy,Partly cloudy throughout the day.,partly-cloudy-day,"remote,65442099999"
4,Ashanti Ghana,2010-01-05,35.3,22.9,27.6,35.5,22.9,28.4,20.8,70.5,...,20.1,8,NaN,2010-01-05T06:19:23,2010-01-05T18:04:21,0.66,Partially cloudy,Partly cloudy throughout the day.,partly-cloudy-day,"remote,65442099999"

In [38]:
weather_df.shape

(24510, 33)

In [39]:
# Check for duplicates
weather_df.duplicated().sum()

0

In [40]:
# Check for missing values
weather_df.isnull().mean()

name                0.000000
datetime            0.000000
tempmax             0.000000
tempmin             0.000000
temp                0.000000
feelslikemax        0.000000
feelslikemin        0.000000
feelslike           0.000000
dew                 0.000000
humidity            0.000000
precip              0.000000
precipprob          0.000000
precipcover         0.000000
preciptype          0.229906
snow                0.054631
snowdepth           0.054876
windgust            0.891677
windspeed           0.000000
winddir             0.000000
sealevelpressure    0.055365
cloudcover          0.000000
visibility          0.054549
solarradiation      0.000000
solarenergy         0.000000
uvindex             0.000000
severerisk          0.895961
sunrise             0.000000
sunset              0.000000
moonphase           0.000000
conditions          0.000000
description         0.000000
icon                0.000000
stations            0.000000
dtype: float64

In [41]:
# Drop irrelevant columns filled with 0's and missing values
weather_df.drop(columns=['snow','snowdepth','windgust','severerisk','sunset','sunrise',
                     'severerisk','icon','stations','moonphase','sealevelpressure','description',
                    'conditions'],inplace=True)

In [42]:
weather_df.columns

Index(['name', 'datetime', 'tempmax', 'tempmin', 'temp', 'feelslikemax',
       'feelslikemin', 'feelslike', 'dew', 'humidity', 'precip', 'precipprob',
       'precipcover', 'preciptype', 'windspeed', 'winddir', 'cloudcover',
       'visibility', 'solarradiation', 'solarenergy', 'uvindex'],
      dtype='object')

In [43]:
# New shape
weather_df.shape

(24510, 21)

In [44]:
# Convert the date to proper format
weather_df['datetime'] = pd.to_datetime(weather_df['datetime'], format='%Y-%m-%d')

In [45]:
weather_df.head(5)

,name,datetime,tempmax,tempmin,temp,feelslikemax,feelslikemin,feelslike,dew,humidity,...,precipprob,precipcover,preciptype,windspeed,winddir,cloudcover,visibility,solarradiation,solarenergy,uvindex
0,Ashanti Ghana,2010-01-01,34.2,23.0,27.9,36.1,23.0,29.3,21.9,73.4,...,0,0.0,NaN,9.0,171.0,48.4,8.7,209.4,18.1,8
1,Ashanti Ghana,2010-01-02,34.6,23.4,28.1,36.5,23.4,29.5,21.7,71.1,...,0,0.0,NaN,8.3,154.2,37.6,8.9,211.2,18.4,7
2,Ashanti Ghana,2010-01-03,35.8,23.7,28.5,36.9,23.7,29.7,21.3,69.0,...,0,0.0,NaN,9.7,161.7,61.2,7.9,220.3,19.1,8
3,Ashanti Ghana,2010-01-04,35.2,23.4,28.2,35.3,23.4,28.9,20.6,68.2,...,0,0.0,NaN,11.9,197.8,81.2,7.5,214.0,18.5,8
4,Ashanti Ghana,2010-01-05,35.3,22.9,27.6,35.5,22.9,28.4,20.8,70.5,...,0,0.0,NaN,11.5,254.3,65.6,7.0,232.6,20.1,8

In [46]:
weather_df[['Country','Region']] = weather_df['name'].str.split(' ',expand=True)

In [47]:
weather_df.drop(columns=['name'],inplace=True)

In [48]:
weather_df.head(5)

,datetime,tempmax,tempmin,temp,feelslikemax,feelslikemin,feelslike,dew,humidity,precip,...,preciptype,windspeed,winddir,cloudcover,visibility,solarradiation,solarenergy,uvindex,Country,Region
0,2010-01-01,34.2,23.0,27.9,36.1,23.0,29.3,21.9,73.4,0.0,...,NaN,9.0,171.0,48.4,8.7,209.4,18.1,8,Ashanti,Ghana
1,2010-01-02,34.6,23.4,28.1,36.5,23.4,29.5,21.7,71.1,0.0,...,NaN,8.3,154.2,37.6,8.9,211.2,18.4,7,Ashanti,Ghana
2,2010-01-03,35.8,23.7,28.5,36.9,23.7,29.7,21.3,69.0,0.0,...,NaN,9.7,161.7,61.2,7.9,220.3,19.1,8,Ashanti,Ghana
3,2010-01-04,35.2,23.4,28.2,35.3,23.4,28.9,20.6,68.2,0.0,...,NaN,11.9,197.8,81.2,7.5,214.0,18.5,8,Ashanti,Ghana
4,2010-01-05,35.3,22.9,27.6,35.5,22.9,28.4,20.8,70.5,0.0,...,NaN,11.5,254.3,65.6,7.0,232.6,20.1,8,Ashanti,Ghana

In [49]:
# Let's drop more irrelevant column to reduce the shape
weather_df.drop(columns=['feelslikemax','feelslikemin', 'feelslike','precipprob',
       'precipcover', 'preciptype'], inplace=True)

In [50]:
weather_df.shape

(24510, 16)

In [51]:
#Weather types
weather_df.dtypes.value_counts()

float64           12
object             2
datetime64[ns]     1
int64              1
dtype: int64

In [52]:
# Filter in data from the past 10 years
mask = (weather_df['datetime'] >= '2013-01-01')
filtered_weather_df = weather_df.loc[mask]

In [53]:
filtered_weather_df.head(5)

,datetime,tempmax,tempmin,temp,dew,humidity,precip,windspeed,winddir,cloudcover,visibility,solarradiation,solarenergy,uvindex,Country,Region
1096,2013-01-01,30.3,16.6,23.6,15.9,64.8,0.0,25.2,38.5,9.3,7.0,240.6,20.8,9,Ashanti,Ghana
1097,2013-01-02,32.4,16.6,24.1,13.2,54.9,0.0,18.7,46.8,10.4,5.6,247.8,21.4,9,Ashanti,Ghana
1098,2013-01-03,30.5,19.7,25.0,16.8,62.8,0.0,9.4,40.9,68.1,5.0,198.4,17.1,8,Ashanti,Ghana
1099,2013-01-04,29.2,18.9,22.8,16.2,67.9,0.0,12.6,357.3,83.4,NaN,141.8,12.1,6,Ashanti,Ghana
1100,2013-01-05,32.4,17.5,24.1,13.7,57.1,0.0,16.2,18.8,83.3,8.0,243.9,21.0,9,Ashanti,Ghana

In [54]:
filtered_weather_df.reset_index()

,index,datetime,tempmax,tempmin,temp,dew,humidity,precip,windspeed,winddir,cloudcover,visibility,solarradiation,solarenergy,uvindex,Country,Region
0,1096,2013-01-01,30.3,16.6,23.6,15.9,64.8,0.0,25.2,38.5,9.3,7.0,240.6,20.8,9,Ashanti,Ghana
1,1097,2013-01-02,32.4,16.6,24.1,13.2,54.9,0.0,18.7,46.8,10.4,5.6,247.8,21.4,9,Ashanti,Ghana
2,1098,2013-01-03,30.5,19.7,25.0,16.8,62.8,0.0,9.4,40.9,68.1,5.0,198.4,17.1,8,Ashanti,Ghana
3,1099,2013-01-04,29.2,18.9,22.8,16.2,67.9,0.0,12.6,357.3,83.4,NaN,141.8,12.1,6,Ashanti,Ghana
4,1100,2013-01-05,32.4,17.5,24.1,13.7,57.1,0.0,16.2,18.8,83.3,8.0,243.9,21.0,9,Ashanti,Ghana
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19025,24505,2023-05-30,31.2,24.9,28.0,24.1,79.5,0.1,19.1,158.3,70.1,21.6,248.6,21.4,9,Central,Ghana
19026,24506,2023-05-31,31.6,26.1,28.3,24.5,80.3,1.3,20.2,205.1,74.7,20.9,283.7,24.8,9,Central,Ghana
19027,24507,2023-06-01,27.8,26.0,27.0,23.4,80.8,9.7,29.9,208.1,99.1,21.0,101.8,8.8,5,Central,Ghana
19028,24508,2023-06-02,27.5,26.2,27.0,23.3,80.5,15.6,32.0,194.3,99.6,20.1,187.9,16.3,7,Central,Ghana
19029,24509,2023-06-03,27.3,26.2,26.7,23.3,81.4,17.7,20.9,216.4,99.6,19.5,107.8,9.2,7,Central,Ghana

In [55]:
filtered_weather_df.columns

Index(['datetime', 'tempmax', 'tempmin', 'temp', 'dew', 'humidity', 'precip',
       'windspeed', 'winddir', 'cloudcover', 'visibility', 'solarradiation',
       'solarenergy', 'uvindex', 'Country', 'Region'],
      dtype='object')

In [56]:
filtered_weather_df

,datetime,tempmax,tempmin,temp,dew,humidity,precip,windspeed,winddir,cloudcover,visibility,solarradiation,solarenergy,uvindex,Country,Region
1096,2013-01-01,30.3,16.6,23.6,15.9,64.8,0.0,25.2,38.5,9.3,7.0,240.6,20.8,9,Ashanti,Ghana
1097,2013-01-02,32.4,16.6,24.1,13.2,54.9,0.0,18.7,46.8,10.4,5.6,247.8,21.4,9,Ashanti,Ghana
1098,2013-01-03,30.5,19.7,25.0,16.8,62.8,0.0,9.4,40.9,68.1,5.0,198.4,17.1,8,Ashanti,Ghana
1099,2013-01-04,29.2,18.9,22.8,16.2,67.9,0.0,12.6,357.3,83.4,NaN,141.8,12.1,6,Ashanti,Ghana
1100,2013-01-05,32.4,17.5,24.1,13.7,57.1,0.0,16.2,18.8,83.3,8.0,243.9,21.0,9,Ashanti,Ghana
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24505,2023-05-30,31.2,24.9,28.0,24.1,79.5,0.1,19.1,158.3,70.1,21.6,248.6,21.4,9,Central,Ghana
24506,2023-05-31,31.6,26.1,28.3,24.5,80.3,1.3,20.2,205.1,74.7,20.9,283.7,24.8,9,Central,Ghana
24507,2023-06-01,27.8,26.0,27.0,23.4,80.8,9.7,29.9,208.1,99.1,21.0,101.8,8.8,5,Central,Ghana
24508,2023-06-02,27.5,26.2,27.0,23.3,80.5,15.6,32.0,194.3,99.6,20.1,187.9,16.3,7,Central,Ghana
24509,2023-06-03,27.3,26.2,26.7,23.3,81.4,17.7,20.9,216.4,99.6,19.5,107.8,9.2,7,Central,Ghana

In [58]:
# Reorder the weather dataset
filtered_weather_df = weather_df[['Country','Region','tempmax', 'tempmin', 'temp', 'dew', 'humidity', 'precip',
       'windspeed', 'winddir', 'cloudcover', 'visibility', 'solarradiation',
       'solarenergy', 'uvindex',]]

In [59]:
filtered_weather_df.head(5)

,Country,Region,tempmax,tempmin,temp,dew,humidity,precip,windspeed,winddir,cloudcover,visibility,solarradiation,solarenergy,uvindex
0,Ashanti,Ghana,34.2,23.0,27.9,21.9,73.4,0.0,9.0,171.0,48.4,8.7,209.4,18.1,8
1,Ashanti,Ghana,34.6,23.4,28.1,21.7,71.1,0.0,8.3,154.2,37.6,8.9,211.2,18.4,7
2,Ashanti,Ghana,35.8,23.7,28.5,21.3,69.0,0.0,9.7,161.7,61.2,7.9,220.3,19.1,8
3,Ashanti,Ghana,35.2,23.4,28.2,20.6,68.2,0.0,11.9,197.8,81.2,7.5,214.0,18.5,8
4,Ashanti,Ghana,35.3,22.9,27.6,20.8,70.5,0.0,11.5,254.3,65.6,7.0,232.6,20.1,8

In [61]:
filtered_weather_df.to_csv('weather_datapreprocessed.csv', index=False)